table Fact_Sales
	lineageTag: c61b137a-5034-40ca-b1a4-ef184f60ecb1

	measure 'Total Sales' =
			
			SUM(Fact_Sales[sales_amount])
		lineageTag: 1d3a917c-a26d-4791-8c63-295045cc057b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Previous Month Sales' =
			
			CALCULATE(
			    [Total Sales],
			    DATEADD(
			        Dim_Date[Date],
			        -1,
			        MONTH
			    )
			)
		lineageTag: d0cc1f37-a3c0-4200-b889-6ae089d11202

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MoM Growth %' =
			
			DIVIDE(
			    [Total Sales] - [Previous Month Sales],
			    [Previous Month Sales]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 22990b20-920e-41ca-a6b6-01b50d4ccc8f

	measure 'Running Total Sales' =
			
			CALCULATE(
			    [Total Sales],
			    FILTER(
			        ALLSELECTED(Dim_Date[Date]),
			        Dim_Date[Date] <= MAX(Dim_Date[Date])
			    )
			)
		lineageTag: 8a3809f0-ff77-47db-bf96-062f786bb95e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sale_id
		dataType: int64
		formatString: 0
		lineageTag: edc77d51-8e74-45ee-933f-2f845f26ff5b
		summarizeBy: sum
		sourceColumn: sale_id

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: ff8fef09-b836-4ae7-9eb3-68dad6c1dce4
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column city
		dataType: string
		lineageTag: 1ef449e7-428c-473c-b6c4-7c9541f23597
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column store_format
		dataType: string
		lineageTag: 607ad525-f63d-4daf-91a5-f499cf0ee882
		summarizeBy: none
		sourceColumn: store_format

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: a29903c1-5291-4839-9c7c-a6f1edcd46bc
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column item
		dataType: string
		lineageTag: fc462be0-79ca-44db-a27d-9d7e4c0ff740
		summarizeBy: none
		sourceColumn: item

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: int64
		formatString: 0
		lineageTag: dd58fdd5-750d-4343-bb08-990db7d0e938
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: int64
		formatString: 0
		lineageTag: 87fa9ec0-9e47-4f5d-b9f0-1ed4fd017573
		summarizeBy: sum
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

	column sales_amount
		dataType: double
		lineageTag: 9040b5a9-a4f8-4b0c-80bf-4606929e362d
		summarizeBy: sum
		sourceColumn: sales_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Fact_Sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\OneDrive - Kumaraguru College of Technology\Assignment\BI\Mini project 1\brewmetrics_sales.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"sale_id", Int64.Type}, {"date", type date}, {"city", type text}, {"store_format", type text}, {"category", type text}, {"item", type text}, {"quantity", Int64.Type}, {"unit_price", Int64.Type}, {"sales_amount", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

